version: '3'
services:
  base_image:
    build:
      context: .
  postgres_host:
    build:
      context: ./docker_compose/postgres_host
    restart: always
    ports: ["5433:5432"]
    container_name: postgres_host
    networks:
      aviation_network:
        aliases:
          - postgres_host
    volumes:
      - ${DATA_DIR}/pg_data:/var/lib/postgresql/data


networks:
  aviation_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450